version: '1'

workers: 3

queue:
  name: local
  buffer_size: 100
  link_wait_time: 10
  strategy: fifo
  load:
    requests: 100
    period: 1000 # in milliseconds

task.state.transitioner:
  name: unreliable


storages:
  link:
  - name: memory

  page:
  - name: memory

filters:
  link:
    - name: unique_from_storage
      storage: 
        name: "memory" # TODO: doesnt look good, needs waiting or config if loaded before `storages`
    - name: facebook
      include: false
    - name: domain
      domain: test.com
    - name: depth
      depth: 5
    # - name: robots
    #   path:
    #     http: https://google.com
  link.strategy: 
    name: cumulative

  content:
    - name: porn
      keywords: ['xxx', 'abc']
    - name: content_type
      include: false
      types: ['text/css', 'image/png']
  content.strategy: 
    name: negative_high

fetchers:
  - name: limit_body
    # size limit in bytes
    limit: 10000

  - name: circuit_breaker # using sony gobreaker
    max_requests: 5
    interval: 2
    timeout: 20

extractors:
  - name: html
